### PR TITLE
Add 'docker' to image

### LINKED ISSUE #102: Can't exec into container
I'm using dockerised version of dockly, and I have multiple containers running, all of them have both sh and bash installed. Other dockly features work well.

## Expected Behavior
A shell inside a container is opened

## Actual Behavior
ERROR spawnsync docker ENOENT

## Steps to Re-produce the Problem

  1. select a container and press "l"

## Context

- Operating System: ubuntu 16.04
- Node.js version (run `node --version`): as in librantal/dockly:latest
- Package version: as in librantal/dockly:latest
- Docker version (run `docker --version`): Docker version 18.09.4, build d14af54
- Is docker installed locally? yes
- Do you have containers created? yes
- Does this file exists `/var/run/docker.sock` ? yes
- Output of `docker info`:
```
Containers: 24
 Running: 24
 Paused: 0
 Stopped: 0
Images: 581
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-041800-lowlatency
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55GiB
Name: sokrates
ID: 2ZT7:CRKC:PFS2:D4UT:HMGU:5Y4N:YEZK:CDPW:IE7J:RZS7:VYHF:DEGN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jbieron
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by bieron**
Fixes #102

# Summary

Installing docker fixes the issue. Downside is that it increases image size from 193 to 380 MB, but I think it's a sacrifice worth making for regaining functionality.
Another minor issue is that, at least for me, exec'ed shell does not show the cursor. Didn't look into that long, `stty echo` did not help. Any thoughts?

## Checklist

- [x] Fixed issue #102

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks @bieron, this is great! 👏

**Comment by lirantal** [comment]
@bieron can you check out the latest dockly image that got built due to this PR being merged and confirm too that the code in this PR made it there? we had issues in the past about the image in Docker Hub being out of date

**Comment by bieron** [comment]
yes, it works fine now. seems startup time's slightly longer, but that's probably be due to other factors

**Comment by lirantal** [comment]
Thank you. Appreciate the PR too, great job!

**Pull request merged**
