### PR TITLE
Refactor/base widgets templates

### PR DESCRIPTION
**Pull request by MatanAvneri**
# Summary
Added widgets templates for list, info and logs widgets

## Proposed Changes

  -

  -

  -

## Checklist

- [ ] I added tests
- [ ] I updated the README if necessary
- [ ] This PR introduces a breaking change
- [ ] Fixed issue #
- [X] I added a picture of a cute animal cause it's fun

image

### CODE REVIEW

**Comment by lirantal** [comment]
Nice refactor!
Only issue I found is Containers and Logs titles are missing

**Comment by MatanAvneri** [comment]
@lirantal your'e right. Labels were missing across the board. Fixed :)

**Comment by lirantal** [comment]
Literally across the board :-)

**Comment by lirantal** [comment]
@MatanAvneri FYI I also published 3.2.0 with this PR.

**Pull request merged**
