### PR TITLE
Added Resizable Log Widget Functionality

### LINKED ISSUE #78: Scroll through logs?
Hi, this tool is already so great. Thanks for your hard work! 

This may already be possible so please feel free to close if so. Is it possible to scroll through the entire logs for a container? The view window is rather small and seems to be truncated by default which makes sense for the dashboard. However, having an option to view the full logs somehow would make this my number 1 docker tool. 

We could have a button at the bottom that opens the full logs in a model similar to `info`. Maybe it happens automatically if you press return twice quickly?

### PR DESCRIPTION
**Pull request by KadenLNelson**
# Summary
Added functionality within log widget template to resize on `-` keypress from a small widget to an expanded widget by modifying the grid layout based upon a boolean parameter `this.isExpanded`. 

The functionality saves the log data previously posted to the widget, destroys the old widget, recreates a resized widget, then repopulates the widget with the log data we've previously saved.

_This isn't final. We can improve upon this foundation I've put into place. Please leave your comments/questions/concerns below. I'm happy to collaborate! 🎉_
## Proposed Changes

  - Key `-` toggles a resize on the log widget from unexpanded to expanded (attempt to fix #78)

## Checklist

- [ ] I added tests
- [ ] I updated the README if necessary
- [ ] This PR introduces a breaking change
- [x] Fixed issue #78
- [x] [I added a picture of a cute animal cause it's fun](https://theculturetrip.com/wp-content/uploads/2016/12/mexican_wolf_2_yfb-edit_2.jpg)

### CODE REVIEW

**Comment by lirantal** [comment]
Good stuff @KadenLNelson.

I like this. I would say that we could probably support the same functionality of minimize/maximize view for the container listing as well, so perhaps it's worth to also detect which widget is being focused and perform the action based on that.

**Comment by triforcely** [comment]
Nice draft - this feature is must have for daily use! I've found some problems though. 
I know this is not final but I'll note them here, so they don't slip through our review process 😄 

1) When maximizing logs focus is not changed - I need to cycle focus with tab before I can scroll through logs. I think that container list under the expanded logs widget can still be focused?
2) When the view is changed even once (press V), expanding logs causes dockly to crash.
3) When logs are expanded while the menu is open ('m'), it appears on top of it but you can still interact with menu (because it has focus).

No. 3 is similar to 1 and is not really a problem introduced in this PR but kind of "inherited" problem of the current implementation. I'll create a separate issue where, where we can discuss our options.

**Comment by KadenLNelson** [comment]
:) Glad to see this is being continued

**Comment by lirantal** [comment]
Yep, I think we're good to land this in :-)

**Pull request merged**
